steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_IMAGE}",
        ".",
        "--build-arg=ATLANTIS_GH_USER=$$ATLANTIS_GH_USER",
        "--build-arg=ATLANTIS_GH_TOKEN=$$ATLANTIS_GH_TOKEN",
        "--build-arg=ATLANTIS_GH_WEBHOOK_SECRET=$$ATLANTIS_GH_WEBHOOK_SECRET",
      ]
    dir: "."
    secretEnv:
      ["ATLANTIS_GH_USER", "ATLANTIS_GH_TOKEN", "ATLANTIS_GH_WEBHOOK_SECRET"]
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/atlantis-gh-user/versions/latest
      env: "ATLANTIS_GH_USER"
    - versionName: projects/$PROJECT_ID/secrets/atlantis-gh-token/versions/latest
      env: "ATLANTIS_GH_TOKEN"
    - versionName: projects/$PROJECT_ID/secrets/atlantis-gh-webhook-secret/versions/latest
      env: "ATLANTIS_GH_WEBHOOK_SECRET"

images: ["${_IMAGE}"]
substitutions:
  _IMAGE: "europe-docker.pkg.dev/<project-id>/<repo-name>/<docker-image-name>:<tag>"
